[versions]
antlr = "4.13.2"
argparse4j = "0.9.0"
caldav4j = "1.0.5"
commonstext = "1.15.0"
emoji4j = "16.0.0"
gradle = "8.12"
graaljs = "25.0.2"
graphviz = "0.18.1"
jackson = "2.21.0"
jda = "6.3.1"
kotlin = "2.3.10"
logback = "1.5.31"
natty = "1.1.2"
poi = "5.5.1"
prettytime = "5.0.9.Final"
sardine = "5.13"
shadow = "8.3.0"


[libraries]
antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
argparse4j = { module = "net.sourceforge.argparse4j:argparse4j", version.ref = "argparse4j" }
caldav4j = { module = "com.github.caldav4j:caldav4j", version.ref = "caldav4j" }
commonstext = { module = "org.apache.commons:commons-text", version.ref = "commonstext" }
emoji4j = { module = "com.sigpwned:emoji4j-core", version.ref = "emoji4j" }
graaljs = { module = "org.graalvm.js:js", version.ref = "graaljs" }
graphviz = { module = "guru.nidi:graphviz-kotlin", version.ref = "graphviz" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
natty = { module = "io.github.natty-parser:natty", version.ref = "natty" }
poi-core = { module = "org.apache.poi:poi", version.ref = "poi" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
prettytime = { module = "org.ocpsoft.prettytime:prettytime", version.ref = "prettytime" }
sardine = { module = "com.github.lookfirst:sardine", version.ref = "sardine" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
